config/routes.rb
Rails.application.routes.draw do
  # Devise маршруты
  devise_for :users

  # Главная страница
  root to: "posts#index"

  # Кастомная страница профиля для текущего пользователя
  resource :profile, controller: 'profiles', only: [:show, :edit, :update]

  # Маршрут для просмотра профиля конкретного пользователя
  get 'user_profiles/:id', to: 'profiles#show', as: :user_profile

  # Маршрут для списка профилей
  resources :profiles, only: [:index]

  get 'friends', to: 'profiles#friends', as: :friends

  resources :posts, only: [:new, :create, :index, :destroy, :edit, :update, :show] do
    resources :comments, only: [:create, :destroy]
    collection do
      get :feed
    end
  end

  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, uniqueness: true, allow_blank: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes

  # Ассоциации для подписчиков и подписок
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :avatar

  # after_commit :resize_avatar, if: -> { avatar.attached? }

  def display_name
    nickname.present? ? nickname : email
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
  end

  def relationship_with(user)
    active_relationships.find_by(followed_id: user.id)
  end

  private

  def resize_avatar
    avatar.variant(resize: "64x64").processed
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path(anchor: "post-#{@post.id}"), notice: 'Комментарий успешно добавлен.' }

        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: 'Ошибка при добавлении комментария.' }
        format.js { render 'error' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post

    # Проверяем права пользователя на удаление комментария
    if @comment.user == current_user
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path(anchor: "post-#{@post.id}"), notice: 'Комментарий успешно удален.' }
        format.js
      end
    else
      redirect_to root_path, alert: 'У вас нет прав на удаление этого комментария.'
    end
  end



  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    if @post.likes.where(user_id: current_user.id).blank?
      @like = @post.likes.create(user_id: current_user.id)
      redirect_to root_path(anchor: "anchor-post-#{@post.id}")
    else
      redirect_to root_path, alert: 'Вы уже ставили лайк этому посту.'
    end
  end

  def destroy
    @like = Like.find(params[:id])
    post = @like.post

    if @like.user == current_user
      @like.destroy
      redirect_to root_path(anchor: "anchor-post-#{post.id}")
    else
      redirect_to root_path, alert: 'Ошибка удаления лайка.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:destroy]

  def index
    @post = current_user.posts.build
    @feed_items = current_user.feed.order(created_at: :desc)
  end

  # def feed
  #   following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
  #   Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: current_user.id)
  # end

  def show
    @post = Post.find_by(id: params[:id])

    if @post.user == current_user
      @post.destroy
      redirect_to root_path, notice: 'Пост успешно удален.'
    else
      redirect_to root_path, alert: 'Ошибка удаления.'
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Пост успешно создан.'
    end
  end


  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to root_path, notice: 'Пост успешно удален.'
    else
      redirect_to root_path, alert: 'Ошибка удаления.'
    end
  end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = params[:id].present? ? User.find(params[:id]) : current_user

    puts "Параметры ID: #{params[:id]}"
    puts "Текущий пользователь: #{current_user.id}"
    puts "@user ID: #{@user.id}"

    @posts = @user.posts.order(created_at: :desc)
  end





  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to profile_path, notice: 'Описание обновлено'
    end
  end


  def index
    if params[:search].present?
      @users = User.where("nickname LIKE ? OR email LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      @search_info = "Результаты поиска для '#{params[:search]}': #{@users.count} пользователей найдено."
    else
      @users = User.all
      @search_info = "Полный список пользователей."
    end
  end


  def friends
    @friends = current_user.following
    if params[:search].present?
      @friends = @friends.where("username LIKE ? OR email LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      @search_info = "Результаты поиска для: #{params[:search]}"
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:description, :nickname, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pluralization_helper.rb
module PluralizationHelper
  def russian_pluralize(number, one, few, many)
    return many if (11..14).include?(number % 100)
    case number % 10
    when 1
      one
    when 2..4
      few
    else
      many
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_like(post)
    post.likes.find_by(user_id: current_user.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_link_tag 'style_main', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_importmap_tags %>
    <meta name="csrf-param" content="authenticity_token" />
    <meta name="csrf-token" content="<%= form_authenticity_token %>" />


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_comments_modal.html.erb
<div class="modal fade" id="commentsModal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="commentsModalLabel-<%= post.id %>" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong><%= post.user.email %></strong>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <p><%= post.description %></p>
        </div>
        <div class="d-flex align-items-center mb-3">
          <% liked = user_like(post) %>
          <% if liked %>
            <%= button_to "Удалить лайк", like_path(liked), method: :delete, remote: true, data: { post_id: post.id, action: "unlike" }, id: "unlike-button-modal-#{post.id}", class: "btn btn-secondary" %>
          <% else %>
            <%= button_to "Лайк", likes_path(post_id: post.id), method: :post, remote: true, data: { post_id: post.id, action: "like" }, id: "like-button-modal-#{post.id}", class: "btn btn-secondary" %>
          <% end %>
          <span class="ml-2"><%= post.likes.count %> <%= russian_pluralize(post.likes.count, 'лайк', 'лайка', 'лайков') %></span>
        </div>
        <hr>
        <% post.comments.each do |comment| %>
          <p id="comment_<%= comment.id %>">
            <strong><%= comment.user.email %></strong>: <%= comment.body %>
            <% if comment.user == current_user %>
              <%= button_to 'Удалить', post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: 'Вы уверены?' } %>
            <% end %>
          </p>
        <% end %>
        <%= form_for [post, Comment.new] do |f| %>
          <%= f.text_area :body, placeholder: "Добавить комментарий..." %>
          <%= f.submit "Комментировать", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_edit_post_modal.html.erb
<div class="modal fade" id="editPostModal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="editPostModalLabel-<%= post.id %>" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong>Редактирование поста</strong>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: post, local: true, html: { class: 'edit-post-form' } do |f| %>
          <%= f.text_area :description, class: "form-control", placeholder: "Что у вас нового?" %>
          <%= f.submit "Сохранить изменения", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="logo-container">
  <%= image_tag("logo.png", alt: "Логотип Twitgram", class: "site-logo") %>
</div>
<h3>Меню</h3>
<ul class="list-unstyled">
  <li><%= link_to "Лента", posts_path, class: "menu-link" %></li>
  <li><%= link_to current_user.nickname, profile_path(current_user), class: "menu-link" %></li>
  <li><%= link_to "Друзья", friends_path, class: "menu-link" %></li>
  <li><%= link_to "Поиск пользователей", profiles_path, class: "menu-link" %></li>
  <li><%= link_to "Редактировать профиль", edit_profile_path, class: "menu-link" %></li>
  <li><%= link_to "Изменить пароль или e-mail", edit_user_registration_path, class: "menu-link" %></li>
  <li><%= button_to "Выйти", destroy_user_session_path, method: :delete, class: "menu-link logout-button" %></li>
</ul>

app/views/shared/_post.html.erb
<div class="post-content" id="anchor-post-<%= post.id %>">
  <div class="user-info flex-container">

    <% if post.user.avatar.attached? %>
      <%= image_tag(post.user.avatar, class: "avatar-feed-small", size: "64x64") %>
    <% else %>
      <%= image_tag("default_avatar.png", class: "avatar-feed-small", size: "64x64") %>
    <% end %>

    <%= link_to post.user.nickname, user_profile_path(post.user), class: "username flex-grow" %>

    <% if current_user == post.user %>
      <%= link_to "Редактировать", edit_post_path(post), class: "edit-post", data: { toggle: "modal", target: "#editPostModal-#{post.id}" } %>
      <%= link_to "Удалить", post_path(post), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить этот пост?' }, class: "delete-post" %>
    <% else %>
      <div class="edit-post-placeholder" style="visibility: hidden;">Редактировать</div>
    <% end %>
  </div>

  <div class="post-divider"></div>

  <div><%= post.description %></div>

  <% if post.image.attached? %>
    <div class="post-image-wrapper">
      <%= link_to rails_blob_url(post.image), target: "_blank" do %>
        <%= image_tag(post.image, class: "post-image") %>
      <% end %>
    </div>
  <% end %>

  <div class="d-flex justify-content-between actions-container">
    <% liked = user_like(post) %>
    <% if liked %>
      <%= button_to like_path(liked), method: :delete, remote: true, data: { post_id: post.id, action: "unlike" }, id: "unlike-button-#{post.id}", class: "no-border-button" do %>
        <%= image_tag("like.png", alt: "Удалить лайк") %>
      <% end %>
    <% else %>
      <%= button_to likes_path(post_id: post.id), method: :post, remote: true, data: { post_id: post.id, action: "like" }, id: "like-button-#{post.id}", class: "no-border-button" do %>
        <%= image_tag("unlike.png", alt: "Лайк") %>
      <% end %>
    <% end %>

    <div class="d-flex justify-content-center align-items-center likes-container" style="flex: 1;">
      <span id="post-<%= post.id %>-likes"><%= post.likes.count %> <%= russian_pluralize(post.likes.count, 'лайк', 'лайка', 'лайков') %></span>
    </div>

    <button type="button" class="comment-button" data-toggle="modal" data-target="#commentsModal-<%= post.id %>">
      <%= image_tag("comment.png", alt: "Комментарии", class: "comment-image") %>
    </button>
  </div>

  <!-- Модальное окно для комментариев -->
  <%= render partial: 'shared/comments_modal', locals: { post: post } %>
  <%= render partial: 'shared/edit_post_modal', locals: { post: post } %>
</div>